# Generated by Django 4.0.2 on 2022-02-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_ae',
            new_name='created_at',
        ),
    ]
